version: '3'
services:
  prisme:
    image: "prismelabs/analytics:dev"
    env_file: "./.env"
    working_dir: "/app"
    command: "/app/server"
    volumes:
      - "./:/app:ro"
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - "prisme.localhost"
