version: '3'
services:
  postgres:
    image: "docker.io/library/postgres:15"
    command: "-c log_statement=all"
    healthcheck:
      test: "/usr/bin/pg_isready"
      timeout: "10s"
    user: "postgres:postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "${PRISME_DATABASE:-prisme}"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./postgres:/docker-entrypoint-initdb.d:ro"
    networks:
      default:
        aliases:
          - "postgres.localhost"

  clickhouse:
    image: "docker.io/clickhouse/clickhouse-server:23.9.1-alpine"
    ports:
      - 8123:8123
    ulimits:
      nofile: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
    volumes:
      - "./migrations:/docker-entrypoint-initdb.d:ro"
      - "clickhouse_data:/var/lib/clickhouse"
    environment:
      CLICKHOUSE_USER: "clickhouse"
      CLICKHOUSE_PASSWORD: "password"
      CLICKHOUSE_DB: "${PRISME_DATABASE:-prisme}"
    networks:
      default:
        aliases:
          - "clickhouse.localhost"

volumes:
  postgres_data:
  clickhouse_data:
